# Generated by Django 4.2.7 on 2023-11-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductivePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_of_measure', models.IntegerField(choices=[(1, 'grams'), (2, 'ounces')])),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('super_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.species')),
            ],
            options={
                'verbose_name_plural': 'Sub-Species',
                'unique_together': {('super_species', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('sub_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.subspecies')),
            ],
            options={
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='ReproductivePartPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pricing_date', models.DateField()),
                ('seeds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crops.reproductivepart')),
            ],
        ),
        migrations.AddField(
            model_name='reproductivepart',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.variety'),
        ),
        migrations.AlterUniqueTogether(
            name='reproductivepart',
            unique_together={('variety', 'weight', 'unit_of_measure')},
        ),
    ]
