# Generated by Django 4.2.7 on 2023-11-19 11:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(help_text='Size in square-meters')),
                ('start_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Land Preparation'), (3, 'Nursery'), (4, 'Growing and Maintenance'), (5, 'Harvesting'), (6, 'Complete')], default=1)),
                ('harvested', models.BooleanField(default=False)),
                ('first_harvest_date', models.DateField(blank=True, null=True)),
                ('last_harvest_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
            },
        ),
        migrations.CreateModel(
            name='FarmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(help_text='Size in square-meters')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('size', models.IntegerField(help_text='Size in square-meters')),
            ],
        ),
    ]
