# Generated by Django 4.2.7 on 2023-11-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('users', '0001_initial'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmorder',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.farmsponsor'),
        ),
        migrations.AddField(
            model_name='farmorder',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crops.variety'),
        ),
        migrations.AddField(
            model_name='farm',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.farmorder'),
        ),
        migrations.AddField(
            model_name='farm',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.site'),
        ),
    ]
